### ISSUE TITLE
Inconsistency in taking pictures

### ISSUE THREAD

**Issue by liy37** [Thukor/MazeSolver#2]
Doesn't take pic sometimes

**Comment by markflorkowski** [comment]
Also, images are always saved in same location with same file name.

**Comment by liy37** [comment]
going back to app after closing resets app

**Comment by markflorkowski** [comment]
Appears to be an issue with the preview texture area size not matching the camera output size.

`W/CameraDevice-JV-0: Stream configuration failed due to: endConfigure:365: Camera 0: Unsupported set of inputs/outputs provided`


`E/CameraCaptureSession: Session 1: Failed to create capture session; configuration failed`

**Comment by Thukor** [comment]
What is the status on this??
